### ISSUE TITLE
The NASA SRTM downloader gets throttled

### ISSUE THREAD

**Issue by janosrusiczki** [agrenott/pyhgtmap#23]
After the tool downloads 5 files I get an authentication error.

```
N44E021: downloading file https://earthexplorer.usgs.gov/download/5e83a43cb348f8ec/SRTM3N44E021V2/EE to /mnt/data/hgt/SRTM3v3.0/N44E021.tif ...
N44E021: using file /mnt/data/hgt/SRTM3v3.0/N44E021.tif.
N45E021: trying srtm3v3.0 ...
N45E021: downloading file https://earthexplorer.usgs.gov/download/5e83a43cb348f8ec/SRTM3N45E021V2/EE to /mnt/data/hgt/SRTM3v3.0/N45E021.tif ...
N45E021: using file /mnt/data/hgt/SRTM3v3.0/N45E021.tif.
N46E021: trying srtm3v3.0 ...
N46E021: downloading file https://earthexplorer.usgs.gov/download/5e83a43cb348f8ec/SRTM3N46E021V2/EE to /mnt/data/hgt/SRTM3v3.0/N46E021.tif ...
N46E021: using file /mnt/data/hgt/SRTM3v3.0/N46E021.tif.
N47E021: trying srtm3v3.0 ...
N47E021: downloading file https://earthexplorer.usgs.gov/download/5e83a43cb348f8ec/SRTM3N47E021V2/EE to /mnt/data/hgt/SRTM3v3.0/N47E021.tif ...
N47E021: using file /mnt/data/hgt/SRTM3v3.0/N47E021.tif.
N48E021: trying srtm3v3.0 ...
N48E021: downloading file https://earthexplorer.usgs.gov/download/5e83a43cb348f8ec/SRTM3N48E021V2/EE to /mnt/data/hgt/SRTM3v3.0/N48E021.tif ...
N48E021: using file /mnt/data/hgt/SRTM3v3.0/N48E021.tif.
N49E021: trying srtm3v3.0 ...
N49E021: downloading file https://earthexplorer.usgs.gov/download/5e83a43cb348f8ec/SRTM3N49E021V2/EE to /mnt/data/hgt/SRTM3v3.0/N49E021.tif ...
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/pyhgtmap/NASASRTMUtil.py", line 779, in downloadAndUnzip_Tif
    os.stat(saveFilename)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/hgt/SRTM3v3.0/N49E021.tif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/bin/pyhgtmap", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyhgtmap/main.py", line 561, in main
    hgtDataFiles = NASASRTMUtil.getFiles(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyhgtmap/NASASRTMUtil.py", line 887, in getFiles
    saveFilename = getFile(area, source)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyhgtmap/NASASRTMUtil.py", line 876, in getFile
    return downloadAndUnzip(url, area, source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyhgtmap/NASASRTMUtil.py", line 762, in downloadAndUnzip
    return downloadAndUnzip_Tif(url, area, source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyhgtmap/NASASRTMUtil.py", line 784, in downloadAndUnzip_Tif
    downloadToFile(url, saveFilename, source)
  File "/opt/venv/lib/python3.11/site-packages/pyhgtmap/NASASRTMUtil.py", line 756, in downloadToFile
    return downloadToFile_SRTMv3(url, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyhgtmap/NASASRTMUtil.py", line 731, in downloadToFile_SRTMv3
    opener = earthexplorerLogin()
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyhgtmap/NASASRTMUtil.py", line 726, in earthexplorerLogin
    res2 = opener.open(req2)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```
So 5 files are downloaded correctly and the 6th file gives an error. I have to wait a few minutes and then try again. I also tried, I am not able to login in the web browser either during this time.

The solution could be to to move the call to `earthExplorerLogin()` from `downloadToFile_SRTMv3` somewhere higher in the stack like in `getFiles` so the login is only called once per all downloads (if there are srtm sources), but I'm not sure I know enough Python to do that.

**Comment by agrenott** [comment]
Fix released in v3.3.
Thanks @janosrusiczki !
