### ISSUE TITLE
New SONN1 downloader not downloading all files for germany

### ISSUE THREAD

**Issue by keenonkites** [agrenott/pyhgtmap#36]
I was testing SONN1 Download last few hours/days.
It works properly so far for:

- Switzerland
- Luxembourg

But unfortunately it does not work for Germany, for some files pyhgtmap tells me that the file does not exist on the server, but if I check directly on the google drive of Sonny all is there.

It complains about the following files (ordered alphabetically):
```
N47E013: no file found on server.
N48E010: no file found on server.
N48E011: no file found on server.
N48E012: no file found on server.
N48E013: no file found on server.
N49E010: no file found on server.
N49E011: no file found on server.
N49E012: no file found on server.
N50E007: no file found on server.
N50E008: no file found on server.
N50E010: no file found on server.
N51E007: no file found on server.
N51E008: no file found on server.
N51E009: no file found on server.
N51E010: no file found on server.
N51E011: no file found on server.
N52E008: no file found on server.
N52E009: no file found on server.
N54E006: no file found on server.
N55E007: no file found on server.
```
But when checking on Sonny's Google Drive (Folder 'DTM Europe 1asec v22 by Sonny' they're existing.

Is the problem on my end, or on the tools end  (pyhgtmap) ? Or probably on the providing end (Google drive) ?

Thanks for checking.
Patrik

**Comment by agrenott** [comment]
Looks like a tricky one. I was indeed able to reproduce (so it's not linked to your API account, reaching some kind of daily download cap or whatever).
The files are actually returned in the search by name part, but a 404 is returned by the API when trying to download their content.
And indeed; using the gdrive web UI, we can see and download them... And that's when the fun starts: after downloading (or actually even just previewing the ZIP archive content) the file manually via the web UI, the exact same download from API works fine! You can try for N47E013 and N48E010 (the 2 I've used so far), I bet they'll now download fine with pyhgtmap.

My guess is that those files were not accessed from some time, and google drive kind of moved them to "cold storage" or similar, and this somehow breaks the API access. I couldn't find any documentation about this behavior so far. 
Some similar bug report: https://issuetracker.google.com/issues/218883121

**Comment by agrenott** [comment]
Looking at the file metadata before/after opening the preview in the UI, here is the only meaningful difference:
![image](https://github.com/agrenott/pyhgtmap/assets/12431371/a0cc0e0a-b919-48d6-bf36-cf6c9cd3dabe)

It's been "viewed".

**Comment by agrenott** [comment]
Got some (false) hope that requesting `https://www.googleapis.com/auth/drive` permission instead of `https://www.googleapis.com/auth/drive.readonly` would solve the issue: it doesn't.

**Comment by agrenott** [comment]
Created https://issuetracker.google.com/issues/312938132

**Comment by keenonkites** [comment]
Thanks for checking and the feedback. Hope that get's somehow solved ....

> You can try for N47E013 and N48E010 (the 2 I've used so far), I bet they'll now download fine with pyhgtmap.

I did run pyhgtmap again agains Germany poly file, but the run didn't download any additional files, the two mentioned ones still do not exist in the SONN1 subdirectory (assuming your tests were also against 1asec files).

In the meantime I'll try to 'sideload' the already downloaded complete Europe tiles by just linking SONN1 in the hgt directory to the already downloaded and unpacked one....
Haven't seen any changed index file that would need to be updated for that.

Cheers Patrik

**Comment by keenonkites** [comment]
Update:
sideloading works.... pyhgtmap still complains about two files not on the server but I can't find them even in the browser:
```
N54E006: no file found on server.
N55E007: no file found on server.
```

**Comment by extremecarver** [comment]
I think related to this - pyhgtmap crashes on a file that does not actually exist (N34E031) - I actually already downloaded all Sonny 1" files into the SONN1 folder. But also no index is created for SONN1.
Tried it with both v3.7 as well as the dev version and both crash.

++ nice -n 17 pyhgtmap --earthexplorer-user=extremecarver --earthexplorer-password=TestmapTestmap --jobs=9 --polygon=/home/contourlines/bounds/cyprus.poly --step=10 --no-zero-contour --void-range-max=-420 --output-prefix=cyprus10m --line-cat=500,100 --start-node-id=10000000 --start-way-id=10000000 --source=sonn1,sonn3,view1,srtm1,view3,srtm3 --max-nodes-per-way=230 --max-nodes-per-tile=0 --pbf --hgtdir=/home/contourlines/hgt -j16
checking if area N36E031 intersects with polygon ... no
checking if area N36E032 intersects with polygon ... no
checking if area N36E033 intersects with polygon ... no
N34E031: trying sonn1 ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/sources/__init__.py", line 76, in get_file
    self.check_cached_file(file_name, resolution)
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/sources/__init__.py", line 57, in check_cached_file
    found_size: int = os.path.getsize(file_name)
  File "/usr/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/contourlines/hgt/SONN1/N34E031.hgt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyhgtmap", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/main.py", line 66, in main
    main_internal(sys.argv[1:])
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/main.py", line 45, in main_internal
    hgtDataFiles = NASASRTMUtil.getFiles(
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 767, in getFiles
    saveFilename = sources_pool.get_file(opener, area, source)
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 738, in get_file
    file_name = self._real_pool.get_source("sonn").get_file(
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/sources/__init__.py", line 87, in get_file
    self.download_missing_file(area, resolution, file_name)
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/sources/sonny.py", line 107, in download_missing_file
    files: list[GoogleDriveFile] = self.gdrive.ListFile(
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/sources/sonny.py", line 77, in gdrive
    gauth.CommandLineAuth()
  File "/usr/local/lib/python3.10/dist-packages/pydrive2/auth.py", line 123, in _decorated
    self.LoadCredentials()
  File "/usr/local/lib/python3.10/dist-packages/pydrive2/auth.py", line 400, in LoadCredentials
    self.LoadCredentialsFile()
  File "/usr/local/lib/python3.10/dist-packages/pydrive2/auth.py", line 427, in LoadCredentialsFile
    self.credentials = self._default_storage.get()
  File "/usr/local/lib/python3.10/dist-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/usr/local/lib/python3.10/dist-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/usr/local/lib/python3.10/dist-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

**Comment by extremecarver** [comment]
here is the error on the current pyhgtmap 3.8.dev13+g9f46e54
(system is Ubuntu 22.04 LTS)

++ nice -n 17 pyhgtmap --earthexplorer-user=extremecarver --earthexplorer-password=TestmapTestmap --jobs=9 --polygon=/home/contourlines/bounds/cyprus.poly --step=10 --no-zero-contour --void-range-max=-420 --output-prefix=cyprus10m --line-cat=500,100 --start-node-id=10000000 --start-way-id=10000000 --source=sonn1,sonn3,view1,srtm1,view3,srtm3 --max-nodes-per-way=230 --max-nodes-per-tile=0 --pbf --hgtdir=/home/contourlines/hgt -j16
checking if area N36E031 intersects with polygon ... no
checking if area N36E032 intersects with polygon ... no
checking if area N36E033 intersects with polygon ... no
N34E031: trying sonn1 ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/sources/__init__.py", line 111, in get_file
    self.check_cached_file(file_name, resolution)
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/sources/__init__.py", line 87, in check_cached_file
    found_size: int = os.path.getsize(file_name)
  File "/usr/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/contourlines/hgt/SONN1/N34E031.hgt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyhgtmap", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/main.py", line 67, in main
    main_internal(sys.argv[1:])
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/main.py", line 45, in main_internal
    hgtDataFiles = NASASRTMUtil.getFiles(
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 762, in getFiles
    saveFilename = sources_pool.get_file(opener, area, source)
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/NASASRTMUtil.py", line 731, in get_file
    file_name = self._real_pool.get_source(source[0:4]).get_file(
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/sources/__init__.py", line 122, in get_file
    self.download_missing_file(area, resolution, file_name)
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/sources/sonny.py", line 111, in download_missing_file
    files: list[GoogleDriveFile] = self.gdrive.ListFile(
  File "/usr/local/lib/python3.10/dist-packages/pyhgtmap/sources/sonny.py", line 81, in gdrive
    gauth.CommandLineAuth()
  File "/usr/local/lib/python3.10/dist-packages/pydrive2/auth.py", line 123, in _decorated
    self.LoadCredentials()
  File "/usr/local/lib/python3.10/dist-packages/pydrive2/auth.py", line 400, in LoadCredentials
    self.LoadCredentialsFile()
  File "/usr/local/lib/python3.10/dist-packages/pydrive2/auth.py", line 427, in LoadCredentialsFile
    self.credentials = self._default_storage.get()
  File "/usr/local/lib/python3.10/dist-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/usr/local/lib/python3.10/dist-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/usr/local/lib/python3.10/dist-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

**Comment by extremecarver** [comment]
My solution so far is as always, replace the files in the view1 folder, and if not present before just edit the index file manually and add the relevant lines. Maybe best solution would be a do not download option, just use files as found in the folders as mentioned via source command and even disrespect the index files.

**Comment by agrenott** [comment]
Actually according to your stack trace, it seems the `~/.pyhgtmap/gdrive-credentials.json` is "invalid", ie. not containing the `_module` key.
This causes an error in the authentication flow to google drive.

**Comment by agrenott** [comment]
> Created https://issuetracker.google.com/issues/312938132

So finally got a useful answer: the behavior is actually expected, due to additional security measures introduced on Google Drive in 2021:
- https://developers.google.com/drive/api/guides/resource-keys
- https://arstechnica.com/gadgets/2021/07/heres-what-that-google-drive-security-update-message-means/

Submitted a PR to handle the infamous `resourceKey` header to PyDrive2 which I use: https://github.com/iterative/PyDrive2/pull/350
