### ISSUE TITLE
ImportError: cannot import name 'AutoRegister' from 'class_registry' on Ubuntu 24.04

### ISSUE THREAD

**Issue by pierrepoulpe** [agrenott/pyhgtmap#60]
Bonjour Aurélien, 

I tried to install on a fresh Ubuntu 24.04 desktop (up to date @ 2024-09-11, nothing installed), from the git version and pip version, and got the same issue : 

```(my_venv) gis@ubuntu-otm:~$ pyhgtmap
Traceback (most recent call last):
  File "/home/gis/my_venv/bin/pyhgtmap", line 5, in <module>
    from pyhgtmap.main import main
  File "/home/gis/my_venv/lib/python3.12/site-packages/pyhgtmap/main.py", line 10, in <module>
    from pyhgtmap import NASASRTMUtil
  File "/home/gis/my_venv/lib/python3.12/site-packages/pyhgtmap/NASASRTMUtil.py", line 16, in <module>
    from pyhgtmap.sources.pool import Pool
  File "/home/gis/my_venv/lib/python3.12/site-packages/pyhgtmap/sources/__init__.py", line 11, in <module>
    from class_registry import AutoRegister, ClassRegistry
ImportError: cannot import name 'AutoRegister' from 'class_registry' (/home/gis/my_venv/lib/python3.12/site-packages/class_registry/__init__.py)
```
I googled a little bit, found [this](https://class-registry.readthedocs.io/en/latest/advanced_topics.html) and try to replace, in pyhgtmap/sources/__init__.py
```
from class_registry import AutoRegister, ClassRegistry
```
by 
```
from class_registry import ClassRegistry
from class_registry.base import AutoRegister
```

and then I get 

```(my_venv) gis@ubuntu-otm:~$ pyhgtmap
Traceback (most recent call last):
  File "/home/gis/my_venv/bin/pyhgtmap", line 5, in <module>
    from pyhgtmap.main import main
  File "/home/gis/my_venv/lib/python3.12/site-packages/pyhgtmap/main.py", line 10, in <module>
    from pyhgtmap import NASASRTMUtil
  File "/home/gis/my_venv/lib/python3.12/site-packages/pyhgtmap/NASASRTMUtil.py", line 16, in <module>
    from pyhgtmap.sources.pool import Pool
  File "/home/gis/my_venv/lib/python3.12/site-packages/pyhgtmap/sources/__init__.py", line 29, in <module>
    class Source(ABC, metaclass=AutoRegister(SOURCES_TYPES_REGISTRY)):  # type: ignore[misc] # Mypy does not understand dynamically-computed metaclasses
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
````
And then, it's beyond my skills scope, sorry ;-)

Am I doing something wrong? Do I have to force a previous version of classregistry as a temporary workaround?

Thank you,

**Comment by agrenott** [comment]
Hi,
Thanks for the report and the finding. I'll pin the version to 4.x for the time being, as Python 3.9 support has been dropped since 4.1.0.
Reference for later: https://class-registry.readthedocs.io/en/latest/upgrading_to_v5.html
